### ISSUE TITLE
Offer a prebuilt runnable image as a package

### ISSUE THREAD

**Issue by janderssonse** [DIGGSweden/DCAT-AP-SE-Processor#12]
To ease the use of DCAT, we could offer a prebuilt image, by doing a small ci-pipe, using the Dockerfile to build. It would ease the usage of DCAT-AP-SE.

Notes: Check that the CI time and GItHubs pipe in the free version is generous enough.
To be over, supersure of license compliance, use a base image from red hats UBI project, or OSADL's "legally reviewed" images.

**Comment by istyf** [comment]
Is ”built with GitHub actions” a requirement here? :)

**Comment by janderssonse** [comment]
No, edited :)

**Comment by jonassodergren** [comment]
> Notes: Check that the CI time and GItHubs pipe in the free version is generous enough.
> To be over, supersure of license compliance, use a base image from red hats UBI project, or OSADL's "legally reviewed" images.

A good start. Not so many builds are expected during this autumn.

**Comment by janderssonse** [comment]
Think we could close this one now @jonassodergren . builds happily and green now after the PR initial hickup was resolved and we have a package.. Hm, should we also open a new "publish the jar" one as it was requested in another topic.

**Comment by jonassodergren** [comment]
Soon. docker pull ghcr.io/diggsweden/dcat-ap-processor:latest doesn't work for me yet.

**Comment by janderssonse** [comment]
it was set as private, now it should be public!

**Comment by jonassodergren** [comment]
Well executed PR, clear and well documented.
