### ISSUE TITLE
Finns det någon plan för vilka användningsområden projektet avser stödja? 

### ISSUE THREAD

**Issue by NicklasAndersson** [DIGGSweden/DCAT-AP-SE-Processor#17]
Ser att det finns en PR för att tillhandahålla en Docker image. Hur ser det ut med planer för ev. SDK via tex maven central? Som ett första steg skulle en .jar i github releases vara mycket användbart. 

För oss skulle det vara en stor fördel om vi inte behövde bygga projektet.

**Comment by jonassodergren** [comment]
Tanken just nu är att prova att PR:en fungerar bra. Sedan ska det finnas en binär (image) att ladda ner via en github release. Du skulle kunna få vara pilotanvändare om några dagar?

**Comment by janderssonse** [comment]
Vi har pratat om att ta oss mot att generellt göra våra kodbaser enklare att nyttja, inte bara leverera kod. Se container-paketet som ett första testskott. @jonassodergren och jag kommer säkerligen prata mer kring detta  men gillar tanken med jaren - ev kan vi kunna sett till att även publicera jaren och enkelt versionshantering i kommande iterationer. Men en sak i taget,

**Comment by NicklasAndersson** [comment]
Tack! Det är kanon att vi får lite insikt i hur er plan ser ut. Det underlättar vår planering av vår integration.

**Comment by jonassodergren** [comment]
@NicklasAndersson Kan det vara så att du borde skriva en rad i denna issue, https://github.com/DIGGSweden/DCAT-AP-SE-Processor/issues/13?
