### ISSUE TITLE
conformsTo

### ISSUE THREAD

**Issue by vesstrom** [diggsweden/DCAT-AP-SE-Processor#19]
### Contact Details

fredrik.vesstrom@bolagsverket.se

### What happened?

When trying to understand how to set the data type (keys and values) for _conformsTo_ attribute I can't see how the mapping is done from the .json to DCAT-AP-SE specification.

According to [https://docs.dataportal.se/dcat/en/#dcat_Distribution-dcterms_conformsTo](https://docs.dataportal.se/dcat/en/#dcat_Distribution-dcterms_conformsTo) and [https://github.com/diggsweden/DCAT-AP-SE-Processor/blob/main/src/main/resources/metadataExample/single/full_example.json](https://github.com/diggsweden/DCAT-AP-SE-Processor/blob/main/src/main/resources/metadataExample/single/full_example.json) the range is _Standard_ (i.e. Title and Description) while, to be able to use the Swagger UI tooling, it should concist of a URL to the yaml or json file with the API specification.

Arbetsförmedlingens rdf-file [https://admin.dataportal.se/store/180/metadata/7079?recursive=dcat](https://admin.dataportal.se/store/180/metadata/7079?recursive=dcat) have the following xml-tag for conformsTo
`<conformsTo rdf:resource="https://taxonomy.api.jobtechdev.se/v1/taxonomy/swagger.json>`

How should I set the URL to the .yaml file in conformsTo?

### Steps To Reproduce

See above

### What did you expect?

The range should be a URL

**Comment by fredriknordlander** [comment]
Maybe a bit hard to find in the documentation, but according to the attributes from DCAT-AP-SE v2 supported in this version.
In the file: https://github.com/diggsweden/DCAT-AP-SE-Processor/blob/main/docs/supported_attributes.md, there are supported
metadata described for the values that the api producer should insert.
According to the table, the property: dcterms:conformsTo refers to an established schema that the described distribution uses. Link to the api spec is added in the “about field”  to be able to test run directly on Sveriges Dataportal.
