### ISSUE TITLE
Ta reda på hur lägger man draft från issue listan till backlog

### ISSUE THREAD

**Issue by fredriknordlander** [diggsweden/DCAT-AP-SE-Processor#27]

**Comment by JessicaPry** [comment]
Det finns ingen mottagare till mejlet du skickade.


Det finns tre vanliga orsaker till att ett mejl inte kommer fram:



1. Du har inte skrivit rätt mejladress. Våra adresser skrivs så här: fornamn.efternamn(at)arbetsformedlingen.se. Ibland kan det också finnas en bokstav mellan för- och efternamnet eller ett mellannamn i adressen. Kontrollera namnet på personen du vill skriva till.


2. Personen du har mejlat jobbar inte längre hos oss.


3. Mejladressen går till en brevlåda som inte finns längre.


Många svar hittar du på arbetsformedlingen.se. Där finns även information om hur du lättast kommer i kontakt med oss.


Observera att du inte kan svara på det här mejlet.




Hälsningar
Arbetsförmedlingen


Meddelande: B654cb8770000.000000000001.0001.mml
Från: ***@***.***
Till: ***@***.***
Ämne: [diggsweden/DCAT-AP-SE-Processor] Ta reda pÃ¥ hur lÃ¤gger man draft frÃ¥n issue listan till backlog (Issue #27)

**Comment by TolgaTurkoglu** [comment]
Intressant inlägg från Jessica Ovan. :) 

@fredriknordlander , du är mycket välkommen att kommentera vad som hände ovan ifall du ser anledningen. För jag misstänker att det inte är Jessica som har skrivit dessa ord. Sedan får vi gärna prata en vända igen om hur vi ser på tavlans och dess kommentarers synlighet för allmänheten.

**Comment by JessicaPry** [comment]
Det finns ingen mottagare till mejlet du skickade.


Det finns tre vanliga orsaker till att ett mejl inte kommer fram:



1. Du har inte skrivit rätt mejladress. Våra adresser skrivs så här: fornamn.efternamn(at)arbetsformedlingen.se. Ibland kan det också finnas en bokstav mellan för- och efternamnet eller ett mellannamn i adressen. Kontrollera namnet på personen du vill skriva till.


2. Personen du har mejlat jobbar inte längre hos oss.


3. Mejladressen går till en brevlåda som inte finns längre.


Många svar hittar du på arbetsformedlingen.se. Där finns även information om hur du lättast kommer i kontakt med oss.


Observera att du inte kan svara på det här mejlet.




Hälsningar
Arbetsförmedlingen


Meddelande: B654d07a80000.000000000001.0001.mml
Från: ***@***.***
Till: ***@***.***
Ämne: Re: [diggsweden/DCAT-AP-SE-Processor] Ta reda pÃ¥ hur lÃ¤gger man draft frÃ¥n issue listan till backlog (Issue #27)

**Comment by TolgaTurkoglu** [comment]
Jag har två lösningsförslag här som jag vill ta upp under nästa möte. Först lite bakgrund:

Man kan se att vi har haft totalt 27 issues hittills inklusive den här issuen. Den äldsta av dessa som fortfarande är öppen är daterat till 2022-04-29. Man kan även se hur ofta dessa issues har genererats. 

Med den bakgrunden så skulle det kunna vara lämpligt med en enkel metod initialt och se ifall det funkar bra.

De förslag som jag har är följande:

1) Vi går igenom våra nya issues tillsammans under angivna ceremonier enligt den arbetsprocess som vi har kommit fram till. Under tiden vi jobbar med DCAT så kommer arbetsgruppen ses och då kan det vara naturligt att ha med det som en punkt i en eller fler av ceremonierna. Det här är också demokratisk eftersom ingen behöver direkt bli ansvarig utan vi hjälps åt tillsammans med att se issues och lägga in dessa som draft sist i backloggen. Enda saken som behöver lösas här är om vi av någon anledning inte behöver ceremonierna eller har några tillfällen kvar att ses regelbundet och då fungerar inte det här.

2) Vi skulle också kunna utse någon som är ansvarig för att gå igenom issues med viss frekvens (något förslag?) eller att om github tillåter prenumeration på nya issues så kan den utsedda personen lägga in dessa i backloggen längst ned. Den här personen behöver inte vara någon PÄ eftersom issues ska bara läggas in i backloggen som en draft. 

Aktivering av en issue från en draft diskuteras inte här eftersom det inte ingår i frågan här.

Själv rekommenderar jag första förslaget, men jag är naturligtvis öppen för alla ideer som kommer från er eller ifall ni tycker att andra förslaget känns bättre för er.

**Comment by JessicaPry** [comment]
Det finns ingen mottagare till mejlet du skickade.


Det finns tre vanliga orsaker till att ett mejl inte kommer fram:



1. Du har inte skrivit rätt mejladress. Våra adresser skrivs så här: fornamn.efternamn(at)arbetsformedlingen.se. Ibland kan det också finnas en bokstav mellan för- och efternamnet eller ett mellannamn i adressen. Kontrollera namnet på personen du vill skriva till.


2. Personen du har mejlat jobbar inte längre hos oss.


3. Mejladressen går till en brevlåda som inte finns längre.


Många svar hittar du på arbetsformedlingen.se. Där finns även information om hur du lättast kommer i kontakt med oss.


Observera att du inte kan svara på det här mejlet.




Hälsningar
Arbetsförmedlingen


Meddelande: B654d0d2c0000.000000000001.0001.mml
Från: ***@***.***
Till: ***@***.***
Ämne: Re: [diggsweden/DCAT-AP-SE-Processor] Ta reda pÃ¥ hur lÃ¤gger man draft frÃ¥n issue listan till backlog (Issue #27)

**Comment by TolgaTurkoglu** [comment]
Efter diskussioner kring det här förra veckan kom vi fram till att vi börjar med förslag 1 ovan och ser ifall det räcker för våra behov.
