### ISSUE TITLE
Docker image build error

### ISSUE THREAD

**Issue by PeterBoos** [DIGGSweden/DCAT-AP-SE-Processor#6]
I'm not entirely sure I'm doing it correctly, but...
When I try to build the docker image in the cloned project I get an error.

I'm on a Windows 10 environment using the command 
`docker buildx build --no-cache -t "dcatprocessor" .`
to build the image. When using 
`docker build --no-cache -t "dcatprocessor" .`
as instructed in readme the log gets to big and clips out and I can't see the error in the log.

A complete log containing the error has been sent to Jonas Södergren by email. Hopefully he can update this issue with more information and/or solution.

/Peter Böös

**Comment by jonassodergren** [comment]
Could you start with allowing larger logs for the build. For docker desktop, Docker Desktop -> Preferences -> Docker Engine -> "features": { "buildkit": false }. Then you can see if 'docker build --no-cache -t "dcatprocessor" .' creates the same problem.

**Comment by PeterBoos** [comment]
Good, thank you for your response. 
I've tried your suggestion and now i can view the entire log. 
It seems the errors persists though. New log file sent over email.

**Comment by jonassodergren** [comment]
@JessicaPry has removed a test case. Now 'docker build' works on windows.

**Comment by PeterBoos** [comment]
I can confirm the problem seems solved, thank you.
